# Generated by Django 3.0.5 on 2020-04-21 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('word', models.CharField(db_index=True, max_length=250)),
                ('pos', models.CharField(max_length=250)),
                ('translation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('oxford_level', models.CharField(max_length=50, null=True)),
                ('audio', models.FileField(blank=True, upload_to='media/audio/')),
                ('topics', models.ManyToManyField(blank=True, db_table='word_topic', related_name='word_topic', to='DictionaryApp.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='UsersWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_users.BotUser')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DictionaryApp.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='UsersTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_users.BotUser')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DictionaryApp.Topics')),
            ],
        ),
    ]
