# Generated by Django 3.0.5 on 2020-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='lang_key',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
