# Generated by Django 3.0.5 on 2020-04-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0002_auto_20200421_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('word', 'pos')},
        ),
    ]
