# Generated by Django 3.0.5 on 2020-04-25 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0006_auto_20200423_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersword',
            name='when_repeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
