# Generated by Django 3.0.5 on 2020-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0007_auto_20200425_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='image',
            field=models.ImageField(null=True, upload_to='media/topic'),
        ),
    ]
