# Generated by Django 3.0.5 on 2020-04-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0008_auto_20200426_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='lang_key',
            field=models.CharField(blank=True, db_index=True, default='end_rus', max_length=20),
        ),
        migrations.AlterField(
            model_name='translation',
            name='pos',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
