# Generated by Django 3.0.5 on 2020-04-26 10:43

import DictionaryApp.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0009_auto_20200426_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=DictionaryApp.models.jsonfield_default_value),
        ),
    ]
