# Generated by Django 3.0.5 on 2020-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0010_auto_20200426_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='oxford_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
