# Generated by Django 3.0.5 on 2020-04-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0011_auto_20200426_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
