# Generated by Django 3.0.5 on 2020-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0012_auto_20200428_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='image',
            field=models.ImageField(null=True, upload_to='topic_img/'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
