# Generated by Django 3.0.5 on 2020-04-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0013_auto_20200428_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
    ]
