# Generated by Django 3.0.5 on 2020-05-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryApp', '0015_usersword_learned_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterModelOptions(
            name='usersword',
            options={'verbose_name': 'Слово пользователя', 'verbose_name_plural': 'Слова пользователя'},
        ),
    ]
