# Generated by Django 3.0.5 on 2020-04-21 22:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0003_auto_20200421_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='words_to_learn',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
