# Generated by Django 3.0.5 on 2020-04-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0004_botuser_words_to_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='notify_time',
            field=models.TimeField(null=True),
        ),
    ]
