# Generated by Django 3.0.5 on 2020-04-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0005_botuser_notify_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='level',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
