# Generated by Django 3.0.5 on 2020-04-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0006_botuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
