# Generated by Django 3.0.5 on 2020-04-29 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0008_botuser_allowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
