# Generated by Django 3.0.5 on 2020-04-29 22:31

import bot_users.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0009_auto_20200429_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='allowed_date',
            field=models.DateTimeField(default=bot_users.models.now_and_more, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последние действия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='notify_time',
            field=models.TimeField(null=True, verbose_name='Уведомления'),
        ),
    ]
