# Generated by Django 3.0.5 on 2020-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0010_auto_20200430_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='lifelong_learning',
            field=models.IntegerField(default=0, verbose_name='Непрерывная серия'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
