# Generated by Django 3.0.5 on 2020-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0011_auto_20200430_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='daily_rating',
            field=models.IntegerField(default=0, verbose_name='Общий рейтинг'),
        ),
    ]
