# Generated by Django 3.0.5 on 2020-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
