# Generated by Django 3.0.5 on 2020-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_supportmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
