# Generated by Django 3.0.5 on 2020-05-02 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_supportmessage_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4000, verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('sended', models.DateTimeField(default=None, null=True, verbose_name='Дата рассылки')),
                ('tested', models.BooleanField(default=False, verbose_name='Проверено?')),
            ],
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'verbose_name': 'Сообщение поддержки', 'verbose_name_plural': 'Сообщения поддержки'},
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Отвечено?'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='chat_id',
            field=models.IntegerField(verbose_name='Id чата'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message_id',
            field=models.IntegerField(verbose_name='Id сообщения'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='reply',
            field=models.CharField(default='', max_length=3000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='text',
            field=models.CharField(max_length=3000, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='username',
            field=models.CharField(default='', max_length=300, verbose_name='Username'),
        ),
    ]
