# Generated by Django 3.0.5 on 2020-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200502_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='count_received',
            field=models.IntegerField(default=0),
        ),
    ]
