# Generated by Django 3.0.5 on 2020-05-01 10:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_users', '0011_auto_20200430_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnd', models.CharField(default='rbk', max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('CR', 'Создан'), ('SC', 'Завершен'), ('FL', 'Ошибка')], default='CR', max_length=2, verbose_name='Статус платежа')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed', models.DateTimeField(default=None, null=True)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='bot_users.BotUser')),
            ],
        ),
    ]
